[build]
  base = "/"
  command = "yarn"
  functions = "functions"
  publish = "dist"
  
[context.production.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.73.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.73.0"