[build]
  command = "hugo"
#  functions = "functions"
  publish = "public"
  
[context.production.environment]
  HUGO_VERSION = "0.84.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"
  PYTHON_VERSION = "3.8"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.84.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.84.0"