[build]
  command = "yarn build"
  functions = "functions"
  publish = "build"
  
[context.production.environment]
  HUGO_VERSION = "0.72.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.72.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.72.0"