[build]
  command = "hugo"
#  functions = "functions"
  publish = "public"
  
[context.production.environment]
  HUGO_VERSION = "0.75.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"
  PYTHON_VERSION = "3.7"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.75.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.75.1"